### ISSUE TITLE
Typo in binary resolution

### ISSUE THREAD

**Issue by RiccardoRiglietti** [nicofirst1/AI_notes#2]
In the `kr_summary.pdf` file. Section 4.2 Resolution Inference Rule.

4.2.1
Binary Resolution

`[Animal(F (x)) ∨ Loves(G(x), x)] and
[Loves(u, v) ∨ ¬Kills(u, v)]`

One of them must be NOT Loves to use resolution right?

**Comment by nicofirst1** [comment]
I'm not really sure (it's been a while since I last studied this).
Could you provide a link or some references in order to back up your claim?

**Comment by RiccardoRiglietti** [comment]
Yes, no problem: https://en.wikipedia.org/wiki/Resolution_(logic)#:~:text=A%20simple%20example%5Bedit%5D

also at page 59 in the same document C9 should be Watered(x) (without the NOT)

(by the way thanks a lot, this material is so valuable for preparing the exam)

**Comment by nicofirst1** [comment]
Thank you for the correction,
If you want to support the notes be sure to share them!
